dist: trusty
language: java
jdk:
  - oraclejdk8
before_script:
  - chmod 777 gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)